apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:RjyUOHv6j24QHWAWdIiHckjrtjcNTL9zqFRjY4yoqvISn2ad,iv:EHX1aohoV8TizNvtd1O/BxxvEFWJOnn0tDf/PnEpQWk=,tag:bp7xIKoh/2ZYv4YizBqUkQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:+GzxiI1G4dK1O9R/v/RK0J+tHUuec21QijIZlOgi6mv+Vo7/gym5aywsVHhd2q7ji2OEep2PD589cp2/pJAux3gKGkz5pN5fd+YjiAr9UZm5gD6IsUFNk9rH6xaHpPJzvNRN5Eb+GVhIVroZTh6sjGTXPUCXGSzfSZu4WsGbaOsPWuRNaJHwRWYPAeuUgj47EOKuStQljKqH68SfIYLqzLT5o7v6AdfbwbLzzAnICg==,iv:aiyAQIGHKtVl095ciDMLOztjc3rButrmlQNkWy985C4=,tag:oisBgSGahM1T1Sw4bpBNCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mgmc8y8hrs8lqq03yke56rk6ad28q0pqhhf9snjpk7cvc3fens7sjcgx4e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQm9RdEN3Y3lzQWNOMEFX
            cHRFT0t0K0tFaU1FbTV1YjlzQ3h0TktGZDBzCjdMMW9kUG5nV0p5ME1aUDRjNmR6
            Wkp1Uzkzd214QnN2SEp6eXp3aW82b0EKLS0tIE9NMXFya0JLOWdUK2dzeVJSQkYx
            NUVCOWNNT0VqRUxkNURXeTc3eUkyc1EKHW4hEim+UQ8ylZC8//XLOTR7KZIJbhlZ
            rTRjH5XvJyNxVmKOnSDv1VmGlunR44Cw/Sdj63GVRrdOxz0QYem0Fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-26T01:21:10Z"
    mac: ENC[AES256_GCM,data:LTjmPbWX4qGgLVV6QRyzRD6KYhSjHRE4SobGxgAGnKlwLy4Zacf/v55b3lHJQy5Scvri7mbPGx812fWVakpkpV+KSjltC8HzhnXBeh61vsPm34hARbnSczoEnH+Su9LJfrXrzdoDVFiUpZnvrWQk3L7OH2OMvHoqHS4T2T3NNhM=,iv:aDjkm94UyA+fCfK90aBm1xEkj3fzuv214708j28suFk=,tag:t6xaGai/si1BpfFfjDheXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
