apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2024.6.1
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  values:
    authentik:
      error_reporting:
        enabled: false
      log_level: "debug"
      server:
        replicas: 1
        image:
          repository: ghcr.io/goauthentik/server
          tag: 2024.12.3
      ingress:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "{{ .Release.Name }}.${SECRET_DOMAIN}"
    postgresql:
      enabled: true
    redis:
      enabled: true
    monitoring:
      enabled: false
      serviceMonitor:
        create: false
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: values.yaml