---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2024.6.1
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2024.6.1
    authentik:
      error_reporting:
        enabled: false
      log_level: "debug"
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.home.arpa/enabled: "true"
      hosts:
        - host: &host "auth.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: *host
          hosts:
            - *host
    postgresql:
      enabled: true
    redis:
      enabled: true
    prometheus:
      serviceMonitor:
        create: false
  valuesFrom:
    - kind: Secret
      name: authentik-secrets