apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: security
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:zUUDaKq/NbYDQ/F4BzRrT2fp55opLyScRJjw/eiMzrbkw7AkjOVoHf1de0SfBers9ja8iVL+kxBMhAAGl/BCXpqs7SgJ3FwasP2h2Fp7hszkt8IVyjGTicat64+VcvEIkc+0jUjBx2Pllx/2O6rvoMWydbBE30fmEctG52sK9UGd86oDwIH5PbGZH1eYB03YVzIIe0oWnzbBoSBQTjsDMpTmtVtMj4QDMKfY/YlMCBZvBZAQsiQUWriC2Pf0geRwlxB7XyJ2X6Yoa2aEf5sbew==,iv:bdH1RhJnkrzShXkIGjQI2XTH5CqNiUsZWuwhHW8RoZo=,tag:T2IPgdMRkiN01kI67tRn2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mgmc8y8hrs8lqq03yke56rk6ad28q0pqhhf9snjpk7cvc3fens7sjcgx4e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeU8rbGVlYmNVanYyL1c2
            WGdLWC9oR1k1QUR6M0FMKzRBWW5qTDVFWENZCnR0eDcvYnFnYkhKT3ZNTHhPZ1I0
            bnR4TU1rVHp3Yjd1QzZlOTlVZENMOWsKLS0tIDQ4MGhhaDNvYVUyM3h0RXBBcmZI
            dVAva1hsa2VaeHcxd2RLcWJtUFIwa2cKyhIqYce1bAvlFt0+pPVaLKmhlkNywo7Q
            p5oRLQkDGyu+VgfB35NMqYNGX4KPQndcvdJa9qSCm9fLSq58lSfvmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-24T02:30:26Z"
    mac: ENC[AES256_GCM,data:VCxSZTiBuivBG2ftWK9ERbamM42KxEVsuRZeJmEG8PmPSoPJMZhC4g4PFAT+kNKLyxKwXMZvBYV8fwg8pn4VHV11WiEkg5CulUvnusYFVQl8G4BNBVZ+1+D2iHGJWWSqpyKBwJepu1sG15iRDVbZq23FW1ERnMjwCFWshkc7/Fc=,iv:DK/r1k58uOBAE/0NpfElnyirU5i3iLjH7ze+2zxwqCo=,tag:VVO6vyCZGxHWg1FJcnTUxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
